# Generated by Django 4.1.4 on 2023-02-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLogoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Logo', 'Logo'), ('Text', 'Text')], max_length=4)),
                ('text', models.CharField(max_length=100, null=True)),
                ('font', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.logo')),
                ('positions', models.ManyToManyField(to='shop.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('positions', models.ManyToManyField(to='shop.position')),
            ],
        ),
        migrations.CreateModel(
            name='MainLogoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Logo', 'Logo'), ('Text', 'Text')], max_length=4)),
                ('text', models.CharField(max_length=100, null=True)),
                ('font', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('additional_positions', models.ManyToManyField(related_name='logo_text_additional_positions', to='shop.position')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.logo')),
                ('positions', models.ManyToManyField(to='shop.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('additional_logo_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_logo_text', to='carts.additionallogotext')),
                ('additional_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.additionalname')),
                ('main_logo_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_text', to='carts.mainlogotext')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.variants')),
            ],
        ),
    ]
